name: Test SSH Connection

on:
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

      - name: Test SSH connection

        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}

          script: |
            echo "Connected successfully"
            hostname
            whoami
            docker --version
